// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Bet struct {
	BetID     int32
	UserID    *int32
	MatchID   *int32
	BetPoints int32
	BetResult *bool
	BetDate   time.Time
	BetValue  int32
}

type Match struct {
	MatchID        int32
	TournamentID   *int32
	Player1ID      int32
	Player2ID      int32
	MatchDate      time.Time
	RoundName      string
	LichessRoundID string
	LichessGameID  *string
	MatchResult    *int32
}

type Player struct {
	PlayerID int32
	Name     string
	Rating   int32
	ImageUrl *string
}

type Tournament struct {
	TournamentID        int32
	Name                string
	StartDate           time.Time
	EndDate             time.Time
	LichessTournamentID string
}

type User struct {
	UserID       int32
	Username     string
	Points       int32
	OauthID      *string
	EmailAddress string
}

type UserPointsHistory struct {
	TransactionID     int32
	UserID            *int32
	TransactionDate   time.Time
	TransactionAmount int32
	RemainingPoints   int32
}
