// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bet struct {
	BetID     int32
	UserID    pgtype.Int4
	MatchID   pgtype.Int4
	BetPoints int32
	BetResult pgtype.Bool
}

type Match struct {
	MatchID               int32
	TournamentID          pgtype.Int4
	Player1               string
	Player2               string
	WinProbabilityPlayer1 float64
	DrawProbability       float64
	WinProbabilityPlayer2 float64
	MatchDate             time.Time
}

type Tournament struct {
	TournamentID int32
	Name         string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
}

type User struct {
	UserID       int32
	Username     string
	Points       int32
	OauthID      pgtype.Text
	EmailAddress string
}

type UserPointsHistory struct {
	TransactionID     int32
	UserID            pgtype.Int4
	TransactionDate   time.Time
	TransactionAmount int32
	RemainingPoints   int32
}
