// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bet struct {
	BetID     int32
	UserID    pgtype.Int4
	MatchID   pgtype.Int4
	BetPoints int32
	BetResult pgtype.Bool
	BetDate   time.Time
	BetValue  int32
}

type Match struct {
	MatchID      int32
	TournamentID pgtype.Int4
	Player1ID    int32
	Player2ID    int32
	MatchDate    time.Time
}

type Player struct {
	PlayerID int32
	Name     string
	Rating   int32
}

type Tournament struct {
	TournamentID int32
	Name         string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
}

type User struct {
	UserID       int32
	Username     string
	Points       int32
	OauthID      pgtype.Text
	EmailAddress string
}

type UserPointsHistory struct {
	TransactionID     int32
	UserID            pgtype.Int4
	TransactionDate   time.Time
	TransactionAmount int32
	RemainingPoints   int32
}
