// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tournaments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (name, start_date, end_date) VALUES ($1, $2, $3) RETURNING tournament_id, name, start_date, end_date
`

type CreateTournamentParams struct {
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament, arg.Name, arg.StartDate, arg.EndDate)
	var i Tournament
	err := row.Scan(
		&i.TournamentID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteTournament = `-- name: DeleteTournament :one
DELETE FROM tournaments WHERE tournament_id = $1 RETURNING tournament_id, name, start_date, end_date
`

func (q *Queries) DeleteTournament(ctx context.Context, tournamentID int32) (Tournament, error) {
	row := q.db.QueryRow(ctx, deleteTournament, tournamentID)
	var i Tournament
	err := row.Scan(
		&i.TournamentID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getTournament = `-- name: GetTournament :one
SELECT tournament_id, name, start_date, end_date FROM tournaments WHERE tournament_id = $1
`

func (q *Queries) GetTournament(ctx context.Context, tournamentID int32) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, tournamentID)
	var i Tournament
	err := row.Scan(
		&i.TournamentID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getTournamentInProgress = `-- name: GetTournamentInProgress :many
SELECT tournament_id, name, start_date, end_date FROM tournaments WHERE start_date <= CURRENT_DATE AND end_date >= CURRENT_DATE
`

func (q *Queries) GetTournamentInProgress(ctx context.Context) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, getTournamentInProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.TournamentID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournamentPast = `-- name: GetTournamentPast :many
SELECT tournament_id, name, start_date, end_date FROM tournaments WHERE end_date < CURRENT_DATE
`

func (q *Queries) GetTournamentPast(ctx context.Context) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, getTournamentPast)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.TournamentID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournamentUpcoming = `-- name: GetTournamentUpcoming :many
SELECT tournament_id, name, start_date, end_date FROM tournaments WHERE start_date > CURRENT_DATE
`

func (q *Queries) GetTournamentUpcoming(ctx context.Context) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, getTournamentUpcoming)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.TournamentID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTournaments = `-- name: GetTournaments :many
SELECT tournament_id, name, start_date, end_date FROM tournaments
`

func (q *Queries) GetTournaments(ctx context.Context) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, getTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.TournamentID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournament = `-- name: UpdateTournament :one
UPDATE tournaments SET name = $2, start_date = $3, end_date = $4 WHERE tournament_id = $1 RETURNING tournament_id, name, start_date, end_date
`

type UpdateTournamentParams struct {
	TournamentID int32
	Name         string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
}

func (q *Queries) UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, updateTournament,
		arg.TournamentID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i Tournament
	err := row.Scan(
		&i.TournamentID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
