// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "dev"
//go:build !wireinject
// +build !wireinject

package services

import (
	"github.com/corentings/chessbet/app/handlers"
	"github.com/corentings/chessbet/infrastructures"
	"github.com/corentings/chessbet/services/bet"
	"github.com/corentings/chessbet/services/match"
	"github.com/corentings/chessbet/services/tournament"
	"github.com/corentings/chessbet/services/user"
)

// Injectors from wire.go:

func InitializeUserHandler() handlers.UserController {
	pool := infrastructures.GetPgxConn()
	iUseCase := user.NewUseCase(pool)
	userController := handlers.NewUserController(iUseCase)
	return userController
}

func InitializeJwtMiddleware() handlers.JwtMiddleware {
	pool := infrastructures.GetPgxConn()
	iUseCase := user.NewUseCase(pool)
	jwtMiddleware := handlers.NewJwtMiddleware(iUseCase)
	return jwtMiddleware
}

func InitializeBetHandler() handlers.BetController {
	pool := infrastructures.GetPgxConn()
	iUseCase := bet.NewUseCase(pool)
	betController := handlers.NewBetController(iUseCase)
	return betController
}

func InitializeTournamentHandler() handlers.TournamentController {
	pool := infrastructures.GetPgxConn()
	iUseCase := tournament.NewUseCase(pool)
	tournamentController := handlers.NewTournamentController(iUseCase)
	return tournamentController
}

func InitializeMatchHandler() handlers.MatchController {
	pool := infrastructures.GetPgxConn()
	iUseCase := match.NewUseCase(pool)
	matchController := handlers.NewMatchController(iUseCase)
	return matchController
}
